### PR TITLE
Add support for SYSCALL

### PR DESCRIPTION
**Pull request by axstin**
This PR lifts syscall instructions into the `__syscall(id, ...)` macro. If the syscall ID is known and a Windows version is set, the appropriate Nt signature is automatically applied. The Nt API can also be set manually.

Nt signatures and syscall ID data are sourced from:
- https://github.com/j00ru/windows-syscalls/blob/master/x64/json/nt-per-system.json
- https://github.com/winsiderss/systeminformer/blob/master/phnt/include/ntzwapi.h

Although this feature pertains more to usermode analysis than kernelmode, I figure it still makes sense in the NtRays project.

Disclaimer: This is my first time messing with IDA's decompiler APIs, let me know if anything could be improved 🙂 

Thanks!

### CODE REVIEW

**Comment by can1357** [comment]
Hey, thanks for the PR!

I do have one suggestion, but if you have no time for it I can still merge it as is since it's a very cool feature regardless.

Instead of the winver selection table, I think it might be nicer to prompt the user to pick a ntdll.dll/ntoskrnl.exe, and then parse the headers there, perhaps using [linux-pe](https://github.com/can1357/linux-pe) to make things easier. 

One somewhat lesser known feature about syscall IDs is that, since they are generated by a linker script, the IDs are assigned linearly with respect to the virtual address each function is placed at. You can do something like this to get essentially the whole table:
```cpp
int32_t is_win32u = 0;
int32_t iterator = 0;
std::vector<std::pair<std::string, uint32_t>> zw_list;
for ( auto& [rva, k] : address_map ) { // e.g. RVA -> Func name from EAT
	if ( !k.starts_with( "Zw" ) )
		continue;
	if ( !is_win32u && k == "ZwGdiGetPixel" )
		is_win32u = 1 << 12;
	syscall_table.emplace_back( k.substr( 2 ), iterator++ );
}
for ( auto& [ref, idx] : syscall_table ) {
	idx |= is_win32u;
}
```

**Comment by axstin** [comment]
Sure, I can work on that. Maybe an option to select an ntdll/ntoskrnl in addition to the existing tables in case the user doesn't have the binary they need available (or they're lazy)? Also neat, didn't know that about the IDs! How future proof do you think your snippet is?

Will look into it 👍

**Comment by can1357** [comment]
It should be pretty feature proof since it's how their system works. Both being available sounds good to me!

**Comment by mrexodia** [comment]
For parsing the source files you can also take a look at this script, which uses libclang to parse PHNT: https://github.com/mrexodia/dumpulator/blob/main/utils/parse_phnt.py. Probably a bit cleaner than the regex hackery you have currently...

**Comment by axstin** [comment]
@mrexodia Yea I was avoiding importing a proper C/C++ parser for whatever reason but that would be cleaner

@can1357 Had success with ntdll. Can ntoskrnl or win32u be enumerated in the same way? With win32u for example, the first ID 0x1000 is assigned to NtUserGetThreadState but isn't the first Nt* export (sorted by RVA)

**Comment by can1357** [comment]
> @mrexodia Yea I was avoiding importing a proper C/C++ parser for whatever reason but that would be cleaner
> 
> @can1357 Had success with ntdll. Can ntoskrnl or win32u be enumerated in the same way? With win32u for example, the first ID 0x1000 is assigned to NtUserGetThreadState but isn't the first Nt* export (sorted by RVA)

Yes sir, thats the little bit trick im doing at the end of the snippet. If you see a Win32u export (in my case i use the Gdi one to detect between ntdll/win32u), you simply or it all with (1<<12). Win32k will not work however since its split IIRC.

Although be careful, you need to use the Zw ones not Nt, Nt ones occasionally have usermode implementations in NTDLL, which screws things up sometimes. NtContinue was one of them IIRC. ZwContinue is fine though.

**Comment by axstin** [comment]
Alrighty, this should be pretty exhaustive

- Added option to parse and extract IDs from ntdll.dll and win32u.dll (saved to IDB)
- Added a bunch of NtUser/NtGdi signatures
- Added a "missing APIs" list (APIs without signatures)

**Comment by can1357** [comment]
Tyvm for the contribution, did not get a chance to test yet but looks good to me!

**Comment by axstin** [comment]
Thanks!

Might've forgotten to add linuxpe to the .vcxproj ... will let you fix that next time you build 👍

**Pull request merged**
